### ISSUE TITLE
Image Issues

### ISSUE THREAD

**Issue by devngc** [MSAtools/UserTools#9]
Images of better quality to be provided for alignment reference. Also, red color from the key plan shall be replaced with black.

**Comment by bijitsony** [comment]
Yes, Totally. Actually I am aware about Image resolution issue and I'll surely find time to solve it ASAP.
Thanks.

**Comment by bijitsony** [comment]
Replaced the Images with better quality, Check it out.
If it's okay to you or not, please let me know.

**Comment by devngc** [comment]
@bijitsony,
Checked them. They're good. Thanks

**Comment by devngc** [comment]
I am going to close this issue now.
